# Generated by Django 2.2.19 on 2023-11-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='укажите название', max_length=150, verbose_name='название товара')),
                ('description', models.TextField(help_text='добавьте описание товара', verbose_name='описание товара')),
                ('price', models.IntegerField(default=0, help_text='укажите цену товара в центах', verbose_name='цена в центах')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'default_related_name': 'item',
            },
        ),
    ]
