version: '3.9'

services:
  payment_project:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
    ports:
     - "8000:8000"
    env_file:
      - ./.env


volumes:
  static_value: